# Generated by Django 5.0.6 on 2025-03-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('summary', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='app/research_files/')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('related_research', models.ManyToManyField(blank=True, related_name='researchers', to='app.research')),
            ],
        ),
    ]
