<template>
  <Header :header-title="result.name" />
  <div class="pt-24 flex flex-col gap-[var(--spacing-between-sections)] w-full">
    <div class="flex flex-col gap-[var(--spacing-in-sections)] w-full">
      <Heading heading="h1" class="text-center">
        {{ result.name }}
      </Heading>
      <PictureWithToolTip
        :image="EventBanner"
        image-alt="Event banner"
        tooltip-text="This picture has been generated by AI. It is not related to the event."
        picture-class="rounded"
      />
    </div>
    <div class="flex flex-col gap-[var(--spacing-in-sections)]">
      <div class="flex gap-[var(--spacing-in-sections)] justify-between w-full">
        <div class="flex gap-[var(--spacing-in-sections)] w-1/3">
          <Text>🗓️</Text>
          <div>
            <Text class="whitespace-nowrap"> {{ formattedDate.date }}, </Text>
            <Text class="whitespace-nowrap">
              {{ formattedDate.time }}
            </Text>
          </div>
        </div>
        <div class="flex gap-[var(--spacing-in-sections)] w-1/3">
          <Text>📍</Text>
          <Text> ??? </Text>
        </div>
      </div>
      <Text>
        {{ result.description }}
      </Text>
    </div>
    <fieldset
      class="fieldset w-full bg-base-200 border border-base-300 p-4 rounded-box"
    >
      <legend class="fieldset-legend">
        <Heading heading="h2"> Sign Up </Heading>
      </legend>

      <label class="fieldset-label">
        <Text small> Name </Text>
      </label>
      <input
        v-model="name"
        type="text"
        class="input"
        placeholder="Name"
        @blur="nameTouched = true"
        :class="{
          'input-error': nameTouched && !name,
          'input-success': nameTouched && name,
        }"
      />

      <label class="fieldset-label">
        <Text small> Email </Text>
      </label>
      <input
        v-model="email"
        type="email"
        class="input"
        :class="{
          'input-error': emailTouched && email && !isValidEmail,
          'input-success': emailTouched && email && isValidEmail,
        }"
        placeholder="Email"
        @blur="emailTouched = true"
      />

      <Text
        v-if="emailTouched && email && !isValidEmail"
        class="text-error mt-1"
        small
      >
        Please enter a valid email address.
      </Text>

      <label class="fieldset-label">
        <Text small> Message </Text>
      </label>
      <textarea
        v-model="message"
        class="textarea"
        placeholder="Message"
      ></textarea>

      <div
        class="w-full flex items-center gap-[var(--spacing-in-sections)] pt-[var(--spacing-in-sections)]"
      >
        <button
          class="btn"
          :class="[
            submitted
              ? 'btn-disabled bg-gray-400 border-gray-400 cursor-not-allowed flex-grow'
              : !isValidEmail || !name || !message
                ? 'btn-disabled opacity-50 cursor-not-allowed w-full'
                : 'btn-primary w-full',
          ]"
          :disabled="submitted || !isValidEmail || !name || !message"
          @click="handleSubmit"
        >
          {{ submitted ? "Already Signed Up" : "Sign Up" }}
        </button>
        <button
          v-if="submitted"
          class="btn btn-secondary"
          @click="exportToICS(result.name, result.date)"
        >
          Export ICS
        </button>
      </div>
    </fieldset>
    <Alert v-if="showConfirmation" class="absolute top-0 right-0 m-4" success>
      <Text> You have successfully signed up for the event! </Text>
    </Alert>
    <div class="flex flex-col gap-[var(--spacing-in-sections)] w-full">
      <Heading heading="h2"> Event Organizer </Heading>
      <Text> Organizer: ??? </Text>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from "vue-router";
import { useApiFetch } from "../api/useApiFetch.ts";
import { computed, onMounted, ref, watch } from "vue";
import type { Events } from "../types/types.ts";
import Header from "../components/Header.vue";
import Heading from "../components/Heading.vue";
import Text from "../components/Text.vue";
import { formatDate, formatTime } from "../utils/dateUtils.ts";
import Alert from "../components/Alert.vue";
import PictureWithToolTip from "../components/PictureWithToolTip.vue";
import EventBanner from "../assets/img/event-banner-ai.png";
import { format } from "date-fns";

const route = useRoute();
const id = route.params.id;

const result = ref<Events>({
  id: 0,
  name: "",
  date: "",
});
const name = ref("");
const email = ref("");
const message = ref("Hi, I'd like to sign up for this event.");
const submitted = ref(false);
const emailTouched = ref(false);
const nameTouched = ref(false);
const showConfirmation = ref(false);

if (localStorage.getItem(`signed-up-${id}`)) {
  submitted.value = true;
}

const { data } = useApiFetch<Events>("events/" + id);

const formattedDate = computed(() => {
  if (result.value.date) {
    const date = formatDate(result.value.date);
    const time = formatTime(result.value.date);
    return {
      date,
      time,
    };
  }
  return { date: "", time: "" };
});

watch(data, () => {
  if (data.value) {
    result.value = data.value;
    message.value = `Hi, I\'d like to sign up for the event "${result.value.name}" on ${formattedDate.value.date} at ${formattedDate.value.time}.`;
  }
});

const isValidEmail = computed(() =>
  /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value),
);

function handleSubmit() {
  if (!name.value || !email.value || !message.value) {
    alert("Please fill out all fields.");
    return;
  }

  console.log("Sending email to organizer...");
  console.log("From:", email.value);
  console.log("Message:", message.value);

  localStorage.setItem(`signed-up-${id}`, "true");
  submitted.value = true;

  showConfirmation.value = true;
  setTimeout(() => (showConfirmation.value = false), 4000);
}

function exportToICS(
  eventTitle: string,
  eventStart: string,
  eventEnd?: string,
) {
  const dtStart = format(new Date(eventStart), "yyyyMMdd'T'HHmmss");
  const dtEnd = format(new Date(eventEnd || eventStart), "yyyyMMdd'T'HHmmss");

  const icsContent = `BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nSUMMARY:${eventTitle}\nDTSTART:${dtStart}\nDTEND:${dtEnd}\nEND:VEVENT\nEND:VCALENDAR`;

  const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${eventTitle.replace(/\s+/g, "_")}.ics`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

onMounted(() => {
  window.scrollTo(0, 0);
});
</script>
