<template>
  <Header headerTitle="Research" />
  <div class="pt-24 flex flex-col items-center justify-center gap-7">
    <div
      class="flex flex-col gap-[var(--spacing-in-sections)] items-end w-full"
    >
      <Text v-if="selectedDate" @click="clearSelectedDate">Remove Filter</Text>
      <Calendar @date-selected="filterByDate" :selected-date="selectedDate" />
    </div>
    <Card
      v-for="event in selectedDate ? filtered : result"
      :key="event.id"
      :card-image="EventBanner"
      card-image-alt="Event Banner"
      :card-title="event.name"
      :card-date="event.date"
      card-text="This is a placeholder text for the event description. It should be replaced with the actual event description."
      button-title="Sign up"
      tooltip-text="This image has been generated by AI. It is not related to the event."
      :link="`/events/${event.id}`"
    />
  </div>
</template>
<script setup lang="ts">
import Card from "../components/Card.vue";
import { ref, watch } from "vue";
import { useApiFetch } from "../api/useApiFetch.ts";
import type { Events } from "../types/types.ts";
import Header from "../components/Header.vue";
import EventBanner from "../assets/img/event-banner-ai.png";
import Calendar from "../components/Calendar.vue";
import Text from "../components/Text.vue";

const result = ref<Events[]>([]);
const filtered = ref<Events[]>([]);
const selectedDate = ref<string | null>(null);

const { data } = useApiFetch<Events[]>("events");

watch(data, () => {
  if (data.value) {
    result.value = data.value;
  }
});

function filterByDate(date: string) {
  selectedDate.value = date;
  filtered.value = result.value.filter((event) => event.date.startsWith(date));
}

function clearSelectedDate() {
  selectedDate.value = null;
  filtered.value = [];
}
</script>
