<template>
  <Header headerTitle="Research" />
  <div class="pt-24 flex flex-col items-center justify-center gap-7">
    <Card
      v-for="event in result"
      :key="event.id"
      :card-image="EventBanner"
      card-image-alt="Event Banner"
      :card-title="event.name"
      :card-date="event.date"
      card-text="This is a placeholder text for the event description. It should be replaced with the actual event description."
      button-title="Sign up"
      tooltip-text="This image has been generated by AI. It is not related to the event."
      :link="`/events/${event.id}`"
    />
  </div>
</template>
<script setup lang="ts">
import Card from "../components/Card.vue";
import { ref, watch } from "vue";
import { useApiFetch } from "../api/useApiFetch.ts";
import type { Events } from "../types/types.ts";
import Header from "../components/Header.vue";
import EventBanner from "../assets/img/event-banner-ai.png";

const result = ref<Events[]>([]);

const { data } = useApiFetch<Events[]>("events");

watch(data, () => {
  if (data.value) {
    result.value = data.value;
  }
});
</script>
