<template>
  <div class="flex flex-col gap-[var(--spacing-between-sections)]">
    <img src="../assets/img/logo.png" alt="logo" />
    <Heading heading="h1" class="">Welcome @ AI Lab</Heading>
    <div class="flex flex-col gap-[var(--spacing-in-sections)]">
      <Heading heading="h2"> Whats new? </Heading>
      <Alert class="alert-dash" info>
        <div class="flex flex-col gap-[var(--spacing-in-sections)]">
          <Text>
            We have our own chat bot for all your questions regarding the AI
            Lab. Have fun exploring!
          </Text>
          <router-link to="/chat">
            <button class="btn btn-primary w-full">Try it out!</button>
          </router-link>
        </div>
      </Alert>
    </div>
    <div class="flex flex-col gap-[var(--spacing-in-sections)]">
      <Heading heading="h2"> Upcoming Events </Heading>
      <Card
        v-for="event in eventsResult"
        :key="event.id"
        :card-image="EventBanner"
        card-image-alt="Event Banner"
        :card-title="event.name"
        :card-date="event.date"
        card-text="This is a placeholder text for the event description. It should be replaced with the actual event description."
        button-title="Sign up"
        tooltip-text="This image has been generated by AI. It is not related to the event."
        :link="`/events/${event.id}`"
      />
    </div>
    <div class="flex flex-col gap-[var(--spacing-in-sections)]">
      <Heading heading="h2"> Research Highlights </Heading>
      <Card
        v-for="research in researchResult"
        :key="research.id"
        :card-image="researchBanner"
        card-image-alt="Research Banner"
        :card-title="research.name"
        :card-text="research.summary"
        button-title="Learn more"
        tooltip-text="This image has been generated by AI. It is not related to the research."
        :link="'/research/' + research.id.toString()"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import Heading from "../components/Heading.vue";
import { ref, watch } from "vue";
import type { Research, Events } from "../types/types.ts";
import { useApiFetch } from "../api/useApiFetch.ts";
import EventBanner from "../assets/img/event-banner-ai.png";
import Card from "../components/Card.vue";
import researchBanner from "../assets/img/research-paper-banner-ai.png";
import Alert from "../components/Alert.vue";
import Text from "../components/Text.vue";

const researchResult = ref<Research[]>([]);
const eventsResult = ref<Events[]>([]);

const { data: researchData } = useApiFetch<Research[]>("research");
const { data: eventsData } = useApiFetch<Events[]>("research");

watch(researchData, () => {
  if (researchData.value) {
    researchResult.value = researchData.value.slice(0, 3);
  }
});

watch(eventsData, () => {
  if (eventsData.value) {
    eventsResult.value = eventsData.value.slice(0, 3);
  }
});
</script>
