<template>
  <div class="flex flex-col gap-[var(--spacing-between-sections)]">
    <router-link to="/chat">
      <FloatChatButton class="fixed top-0 right-0 m-4 z-10" />
    </router-link>
    <img src="../assets/img/logo.png" alt="logo" />
    <Heading heading="h1" class="">Welcome @ AI Lab</Heading>
    <div class="flex flex-col gap-[var(--spacing-in-sections)]">
      <Heading heading="h2"> Whats new? </Heading>
      <Alert class="alert-dash" info>
        <div class="flex flex-col gap-[var(--spacing-in-sections)]">
          <Text>
            We have our own chat bot for all your questions regarding the AI
            Lab. Have fun exploring!
          </Text>
          <router-link to="/chat">
            <button class="btn btn-primary w-full">Try it out!</button>
          </router-link>
        </div>
      </Alert>
    </div>
    <div class="flex flex-col gap-[var(--spacing-in-sections)]">
      <Heading heading="h2"> Upcoming Events </Heading>

      <CardCarousel
        :items="eventsResult"
        :banner-image="EventBanner"
        banner-image-alt="Event Banner"
        placeholder-text="This is a placeholder text for the event description. It should be replaced with the actual event description."
        link="/events/"
      />
    </div>
    <div class="flex flex-col gap-[var(--spacing-in-sections)]">
      <Heading heading="h2"> Research Highlights </Heading>
      <CardCarousel
        :items="researchResult"
        :banner-image="ResearchBanner"
        banner-image-alt="Research Banner"
        tooltip-text="This image has been generated by AI. It is not related to the research."
        link="/research/"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import Heading from "../components/Heading.vue";
import { ref, watch } from "vue";
import type { Research, Events } from "../types/types.ts";
import { useApiFetch } from "../api/useApiFetch.ts";
import EventBanner from "../assets/img/event-banner-ai.png";
import ResearchBanner from "../assets/img/research-paper-banner-ai.png";
import Alert from "../components/Alert.vue";
import Text from "../components/Text.vue";
import CardCarousel from "../components/CardCarousel.vue";
import FloatChatButton from "../components/FloatChatButton.vue";

const researchResult = ref<Research[]>([]);
const eventsResult = ref<Events[]>([]);

const { data: researchData } = useApiFetch<Research[]>("research");
const { data: eventsData } = useApiFetch<Events[]>("events");

watch(researchData, () => {
  if (researchData.value) {
    researchResult.value = researchData.value.slice(0, 3);
  }
});

watch(eventsData, () => {
  if (eventsData.value) {
    eventsResult.value = eventsData.value.slice(0, 3);
  }
});
</script>
