<template>
  <div class="flex flex-col gap-[var(--spacing-in-sections)]">
    <PictureWithToolTip
      :image="NotFoundPicture"
      image-alt="Not Found Picture"
      tooltip-text="This picture has been generated by AI."
      picture-class="rounded"
    />
    <Heading heading="h1">Not Found</Heading>
    <Text>Sorry, the page you are looking for does not exist.</Text>
    <router-link to="/">
      <button class="btn btn-primary w-full">Go back to Home</button>
    </router-link>
  </div>
</template>
<script setup lang="ts">
import Heading from "../components/Heading.vue";
import Text from "../components/Text.vue";
import PictureWithToolTip from "../components/PictureWithToolTip.vue";
import NotFoundPicture from "/img/not-found-portrait-ai.png";
</script>
