<template>
  <Header headerTitle="Research" />
  <div class="pt-20 flex flex-col items-center justify-center gap-7">
    <Card
      v-for="research in result"
      :key="research.id"
      :card-image="researchBanner"
      card-image-alt="Research Banner"
      :card-title="research.name"
      :card-text="research.summary"
      button-title="Learn more"
      tooltip-text="This image has been generated by AI. It is not related to the research."
      :link="'/research/' + research.id.toString()"
    />
  </div>
</template>
<script setup lang="ts">
import Card from "../components/Card.vue";
import { ref, watch } from "vue";
import { useApiFetch } from "../api/useApiFetch.ts";
import type { Research } from "../types/types.ts";
import Header from "../components/Header.vue";
import researchBanner from "../assets/img/research-paper-banner-ai.png";

const result = ref<Research[]>([]);

const { data } = useApiFetch<Research[]>("research");

watch(data, () => {
  if (data.value) {
    result.value = data.value;
  }
});
</script>
